repos:
  - repo: git@github.com:psf/black.git
    rev: "24.10.0"
    hooks:
      - id: black
        language_version: python

  - repo: git@github.com:pycqa/flake8.git
    rev: "7.1.1"
    hooks:
      - id: flake8

  - repo: git@github.com:pre-commit/mirrors-isort.git
    rev: "v5.10.1"
    hooks:
      - id: isort
        language_version: python

  - repo: git@github.com:charliermarsh/ruff.git
    rev: "v0.0.239"
    hooks:
      - id: ruff
        language_version: python
        args: ["--fix"]